### ISSUE TITLE
Support for API V2

### ISSUE THREAD

**Issue by programuotojasgf** [henkmeulekamp/opsgenie-dotnet-client#2]
The API V1 will soon be unsupported(2018.06.30). Do you plan to update this to work with the OpsGenie API V2?

**Comment by henkmeulekamp** [comment]
Ah good point, need to change this. Will do this in coming days.

**Comment by henkmeulekamp** [comment]
Moved up to V2.
Also moved into.net 4.7

**Comment by programuotojasgf** [comment]
It looks live you've used the wrong source for the nugget you pushed. It does not match what's expected from the ReadMe, or more important, from your own unit tests. At least the config class looks like this, should not look like this. Note the ApiUrl. :

```
namespace OpsGenieApi
{
    public class OpsGenieClientConfig
    {
        public OpsGenieClientConfig();

        public string ApiKey { get; set; }
        public string ApiUrl { get; }
    }
}
```

**Comment by henkmeulekamp** [comment]
The config has been changed to not include the url. Need to update the readme.   
  
The url is hardcoded, doesn't need to change ever? 
```
namespace OpsGenieApi
{
    public class OpsGenieClientConfig
    {
        public string ApiUrl => "https://api.opsgenie.com/v2/alerts";
        public string ApiKey { get; set; }
    }
}
```

**Comment by programuotojasgf** [comment]
I understand that's the idea, but the code in the nugget does not have the URL hardcoded. It's not the same code as in the git repository. Maybe something else is also missing then?

**Comment by henkmeulekamp** [comment]
The package downloaded from nuget does show the url being hardcoded:
![image](https://user-images.githubusercontent.com/750315/43121527-5bc0dac6-8f1e-11e8-9e03-4e062caca920.png)
